import { createFileRoute } from "@tanstack/react-router";
import { lazy, Suspense } from "react";
import { Loader2, MapPin } from "lucide-react";
import { useEffect, useState } from "react";
import type { RiskZone } from "@/components/RiskMap";

const RiskMap = lazy(() => import("@/components/RiskMap").then((m) => ({ default: m.RiskMap })));

export const Route = createFileRoute("/map")({
  head: () => ({
    meta: [
      { title: "Live Risk Map — AgriPredict" },
      { name: "description", content: "Interactive geospatial map showing real-time pest outbreak risk zones across your fields." },
    ],
  }),
  component: MapPage,
});

function MapPage() {
  const [riskZones, setRiskZones] = useState<RiskZone[]>([]);

  useEffect(() => {
    fetch("/api/zones")
      .then((res) => res.json())
      .then((data) => setRiskZones(data))
      .catch((err) => console.error("Failed to fetch risk zones:", err));
  }, []);

  const counts = riskZones.reduce<Record<string, number>>((a, z) => ({ ...a, [z.level]: (a[z.level] ?? 0) + 1 }), {});
  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <div className="text-xs uppercase tracking-widest text-primary font-semibold flex items-center gap-2">
            <MapPin className="w-3.5 h-3.5" /> Geospatial intelligence
          </div>
          <h1 className="mt-2 text-3xl sm:text-4xl font-bold">Live Pest Risk Map</h1>
          <p className="mt-2 text-sm text-muted-foreground max-w-2xl">
            Real-time outbreak probability overlaid on your operational territory. Hover any zone for details.
          </p>
        </div>
        <div className="flex gap-3">
          <Stat label="High" value={counts.HIGH ?? 0} bg="bg-risk-high/10" border="border-risk-high/30" text="text-risk-high" />
          <Stat label="Medium" value={counts.MEDIUM ?? 0} bg="bg-risk-medium/10" border="border-risk-medium/30" text="text-risk-medium" />
          <Stat label="Low" value={counts.LOW ?? 0} bg="bg-risk-low/10" border="border-risk-low/30" text="text-risk-low" />
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-5">
        <div className="lg:col-span-3 rounded-2xl border border-border bg-card p-2 shadow-card">
          <Suspense
            fallback={
              <div className="h-[520px] rounded-xl bg-muted flex flex-col items-center justify-center gap-3 text-sm text-muted-foreground">
                <Loader2 className="w-6 h-6 animate-spin text-primary" />
                Fetching live data...
              </div>
            }
          >
            <RiskMap riskZones={riskZones} />
          </Suspense>
        </div>

        <aside className="space-y-5">
          <div className="rounded-2xl border border-border bg-card p-5 shadow-card">
            <div className="text-xs uppercase tracking-widest text-muted-foreground font-semibold mb-3">Legend</div>
            <ul className="space-y-2.5 text-sm">
              <LegendRow color="bg-risk-high" label="High risk" desc="Outbreak probability > 80%" />
              <LegendRow color="bg-risk-medium" label="Medium risk" desc="Probability 40–80%" />
              <LegendRow color="bg-risk-low" label="Low risk" desc="Probability < 40%" />
            </ul>
          </div>

          <div className="rounded-2xl border border-border bg-card p-5 shadow-card">
            <div className="text-xs uppercase tracking-widest text-muted-foreground font-semibold mb-3">Active alerts</div>
            <ul className="space-y-3">
              {riskZones.slice(0, 4).map((z) => (
                <li key={z.id} className="flex gap-3 items-start">
                  <span
                    className={`mt-1 w-2.5 h-2.5 rounded-full shrink-0 ${
                      z.level === "HIGH" ? "bg-risk-high" : z.level === "MEDIUM" ? "bg-risk-medium" : "bg-risk-low"
                    }`}
                  />
                  <div>
                    <div className="text-sm font-medium leading-snug">{z.label}</div>
                    <div className="text-[11px] text-muted-foreground font-mono">
                      {z.lat.toFixed(3)}, {z.lng.toFixed(3)}
                    </div>
                  </div>
                </li>
              ))}
            </ul>
          </div>

          <div className="rounded-2xl border border-border bg-primary/5 p-5">
            <div className="text-xs uppercase tracking-widest text-primary font-semibold mb-1">Map source</div>
            <p className="text-xs text-muted-foreground">
              Tiles &copy; OpenStreetMap · Risk overlay generated by AgriPredict ML pipeline using OpenWeather + satellite NDVI.
            </p>
          </div>
        </aside>
      </div>
    </div>
  );
}

function Stat({ label, value, bg, border, text }: { label: string; value: number; bg: string; border: string; text: string }) {
  return (
    <div className={`rounded-xl px-3 py-2 border ${bg} ${border}`}>
      <div className={`text-2xl font-bold font-display tabular-nums ${text}`}>{value}</div>
      <div className="text-[10px] uppercase tracking-widest text-muted-foreground">{label}</div>
    </div>
  );
}

function LegendRow({ color, label, desc }: { color: string; label: string; desc: string }) {
  return (
    <li className="flex items-start gap-3">
      <span className={`mt-1.5 w-3 h-3 rounded-full ${color} ring-2 ring-background`} />
      <div>
        <div className="font-medium">{label}</div>
        <div className="text-xs text-muted-foreground">{desc}</div>
      </div>
    </li>
  );
}
